# Site settings
title: RubyGSoC
description: The Ruby Google Summer of Code project!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rubygsoc.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: rubygsoc
user_description:
email:
github_username:  rubygsoc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Getting Involved
    url: /getting_involved

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
